version: 0.2

env:
    variables:
        NODE_ENV: production

phases:
    install:
        runtime-versions:
            nodejs: 12

    pre_build:
        commands:
            - echo Installing source NPM dependencies...
            - cd demo
            - npm install
    build:
        commands:
            - cd demo
            - echo Build started on `date`
            - npm run build
            # Sync assets with S3 bucket
            - aws s3 sync demo/dist/ s3://$S3_BUCKET --cache-control "max-age=31536000" --delete
            # Invalidate cloudfront distribution
            - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
