version: 0.2

env:
    variables:
        KEY: VALUE
        NODE_OPTIONS: --max_old_space_size=4096

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Nothing to do in the install phase...

    pre_build:
        commands:
            - pwd
            - echo Installing source NPM dependencies...
            - cd demo
            - npm install
    build:
        commands:
            - pwd
            - echo Build started on `date`
            - npm run build
            # Sync assets with S3 bucket
            - aws s3 sync demo/dist/ s3://$S3_BUCKET --cache-control "max-age=31536000" --delete
            # Invalidate cloudfront distribution
            - aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"
